# Fusión del histórico de monitoreo de contaminantes atmosféricos en la ZMG (1996 a 2023)

**Programación de Análisis de Datos (PRIMAVERA 2025)**  

**Presenta:** Luis Tristán Franco Valdivia (734251), Ingeniería Ambiental

## Alcance ##
El presente proyecto se relaciona con la gestión de datos de calidad del aire al homogeneizar y fusionar múltiples bases de datos sobre parámetros de contaminación atmosférica en la Zona Metropolitana de Guadalajara (ZMG) desde **1996** hasta **2023** (27 años de monitoreo). Gracias al uso de la biblioteca **Pandas**, se logró estructurar y unificar los registros históricos, permitiendo su procesamiento eficiente. Además, la implementación de **Streamlit** optimizó la comunicación de los resultados al proporcionar una interfaz interactiva y accesible para la exploración y visualización de datos. Este enfoque pretende facilitar el acceso y manejo de información clave para la toma de decisiones y la formulación de políticas de calidad del aire basadas en datos sólidos y organizados.

## 1. Recolección de datos ##

La Secretaría de Medio Ambiente y Desarrollo Territorial (**SEMADET**) pone a disposición un conjunto de bases de datos anuales (formato .xlsx) sobre la calidad del aire, accesible a través del **Portal Aire Jalisco**. Este repositorio abarca información histórica desde 1996 hasta 2023, incluyendo datos sobre las concentraciones horarias de distintos contaminantes criterio, registrados en estaciones de monitoreo ubicadas en la ZMG. Los **contaminantes criterio** se definen como aquellas sustancias emitidas en grandes cantidades por diversas fuentes, que representan un riesgo para la salud.


El Sistema de Monitoreo Atmosférico de Jalisco (**SIMAJ**) destaca que las estaciones de monitoreo de la calidad del aire son casetas cerradas que contienen analizadores para la medición diferentes contaminantes, sensores meteorológicos y sistemas para la adquisición y manejo de datos, cada estación con un radio de representatividad de 2 km. Actualmente, hay 13 estaciones meteorológicas distribuidas en El Salto, Guadalajara, Tlaquepaque, Tlajomulco, Tonalá y Zapopan.

<center><img src="./Recolección de datos/Imagen1.png" style="width:900px;height:350px;" class="center"></center>

La base de datos más reciente (2023) contiene información de los siguientes contaminantes criterio y parámetros meteorológicos de acuerdo con el orden y unidades presentadas.  

**Contaminantes criterio:**  
* Ozono (O3), medido en ppm
* Óxido de Nitrógeno (NO), medido en ppm
* Bióxido de Nitrógeno (NO2), medido en ppm
* Óxidos de Nitrógeno (NOX), medido en ppm
* Bióxido de Azufre (SO2), medido en ppm
* Monóxido de Carbono (CO), medido en ppm 
* Partículas menores a 10 micrómetros (PM10), medido en µg/m^3 
* Partículas menores a 2.5 micrómetros (PM2.5), medido en µg/m^3
  
**Parámetros meteorológicos:**
* Temperatura Interna (TMPI), medido en °C
* Temperatura Externa (TMP), medido en °C
* Humedad relativa (RH), medido en porcentaje (%)
* Velocidad de viento (WS), medido en m/s
* Dirección de viento (WD), medido en grados (°)
* Precipitación (PP), medido en (mm)
* Radiación Solar (RS), medido en (W/m^2)
* Presión barométrica (PBA), medido en mbar
* Índice UV (UVI)

## 2. Caracterización de las bases de datos:
### Periodo 1996-2011
La estructura general de la base de datos se compone de 4 tipos de columnas de acuerdo con la información registrada: 
* Columna “FECHA”: Contiene las fechas en las que se realizaron las mediciones.
* Columna “CLAVE_EST”: Contiene las claves de las estaciones de monitoreo.
* Columna "PARAMETRO": Enumera los contaminantes y parámetros meteorológicos monitoreados en cada estación de monitoreo. 
* Columnas “HORA”: Representan las 24 horas del día ("HORA01" a "HORA24") y muestran las mediciones horarias de cada contaminante o parámetro.

<center><img src="./Archivos/Imagenes/Imagen2.png" style="width:900px;height:250px;" class="center"></center>

### Periodo 2012-2018 y 2021
La estructura general de la base de datos se compone de 3 tipos de columnas de acuerdo con la información registrada. Además, en este periodo cada hoja del archivo corresponde exclusivamente al histórico de una estación de monitoreo en particular. 
* Columna sobre fecha de monitoreo: El nombre de esta columna varía según los años. Algunos nombres son “Date” (2012), “Fecha” (2013-2017, 2021) y “FECHA” (2018).
* Columna sobre hora de monitoreo: El nombre de esta columna varía según los años. Algunos nombres son “Time” (2012), “Hora” (2013-2017, 2021) y “HORA” (2018).
* Columnas sobre concentración de contaminantes y parámetros meteorológicos: El nombre de estas columnas varía según los años.
* La base de datos del 2021 contiene una columna adicional, “Estación SIMAJ”. 

<center><img src="./Archivos/Imagenes/Imagen3.png" style="width:900px;height:250px;" class="center"></center>


El nombre de los parámetros de monitoreo, así como el nombre de las hojas de cálculo (estaciones de monitoreo), de las bases de datos originales varía a lo largo del rango de años:


<center><img src="./Archivos/Imagenes/Imagen4.png" style="width:950px;height:400px;" class="center"></center>

### Periodo 2019-2023
La estructura general de la base de datos, que poseen una única hoja en cada archivo, se compone de 3 tipos de columnas de acuerdo con la información registrada. 
* Columna sobre fecha de monitoreo: El nombre de esta columna varía según los años. Algunos nombres son  “Fecha” (2019), “FECHA” (2020) y “Date_Time” (2022-2023).
* Columna sobre hora de monitoreo: El nombre de esta columna varía según los años. Algunos nombres son “Hora” (2019, 2022 y 2023) y “HORA” (2020).
* Columnas sobre concentración de contaminantes y parámetros meteorológicos: El nombre de estas columnas varía según los años.
* Columna sobre estación meteorológica: El nombre de esta columna varía según los años. Algunos nombres son “Estación” (2019, 2022 y 2023) y “ESTACIÓN” (2020).

<center><img src="./Archivos/Imagenes/Imagen5.png" style="width:900px;height:250px;" class="center"></center>

El nombre de los parámetros de monitoreo en las bases de datos originales varía a lo largo del rango de años:

<center><img src="./Archivos/Imagenes/Imagen6.png" style="width:600px;height:350px;" class="center"></center>

## 3.Homogenización y fusión de bases de datos
En este proyecto, se decidió que la estructura indicada para homogeneizar las bases de datos respetaría el orden donde los renglones contienen el comportamiento de todos los parámetros de monitoreo en una hora específica del día.

In [1]:
import pandas as pd

In [3]:
# Crear carpeta para los archivos procesados
carpeta_salida = './Archivos/Datos/Homogeneizados'

### Periodo 1996-2011
Para homogeneizar los datos monitoreo de la calidad del aire desde **1996** a **2011** se deben tener en cuenta los siguientes puntos: 
1. Se desea invertir la estructura de las bases de datos al transformar las horas en renglones y los parámetros en columnas.
2. La hora 01 del día corresponderá a las `01:00:00` horas, mientras que la hora 24 se considerará las `00:00:00` del día posterior.
3. El archivo `datos_2011` tiene una columna adicional llamada `INVALIDA` que debe ser removida.
4. También, el archivo `datos_2011` contiene datos del 31 de diciembre de 2010 que deberán ser eliminados.

La metodología de homogenización se presenta a continuación:

1. Uso del método `.melt()` en la biblioteca pandas para reestructurar los datos al transformar columnas en filas. En este caso, el método convierte las columnas de horas (`HORA01`, `HORA02`, etc.) en filas bajo una columna llamada `HORA`. Los parámetros claves del método son: 
- `id_vars`: Las columnas que se desean conservar o no se necesitan invertir a renglones (`CLAVE_EST`, `FECHA` y `PARAMETRO`).
- `value_vars`: Las columnas que se beben convertir en filas (`HORA 01` a `HORA 24`). 
- `var_name`: El nombre de la nueva columna que contendrá los nombres de las columnas invertidas (`HORA`).
- `value_name`: El nombre de una nueva columna que contendrá los valores de las columnas invertidas (`VALOR`).

2. Se extrajeron los números de las horas mediante `.str.replace()` y se convirtieron en valores enteros con `.astype(int)`. Posteriormente, esos valores numéricos (como 0, 1, 2, etc.) se trasformaron en un formato de hora (`hh:mm:ss`) mediante `.to_timedelta()`.

3. Cada elemento de la columna `PARAMETRO` (como CO, NO2, etc.) se convirtió en una columna única, con sus valores medidos correspondientes, mediante `.pivot_table()` con la siguiente configuración de parámetros del método: 
- `index`: Define los renglones (`CLAVE`, `FECHA` y `HORA`).
- `columns`: Define qué elementos se convierten en columnas (`PARAMETRO`).
- `values`: Especifica qué datos se agregan y organizan (`VALOR`).
- `aggfunc`: Aplica una función de agregación (`mean` evita duplicados)

4. Respecto al archivo `datos_2011`, se eliminó la columna `INVALIDA` con el método `.drop()`.

In [5]:
# Procesar los archivos de 1996 a 2011, uno por uno
for año in range(1996,2011+1):
    print(f"Procesando: datos_{año}.xlsx")  # Mensaje de seguimiento

    # Cargar archivo Excel
    df = pd.read_excel(f'./Archivos/Datos/datos_{año}.xlsx')

    # Eliminar la columna "INVALIDA" si existe
    if 'INVALIDA' in df.columns:
        df = df.drop(columns=['INVALIDA'])

    # Aplicar homogeneización
    df_melted = df.melt(
        id_vars=['CLAVE_EST', 'FECHA', 'PARAMETRO'],
        value_vars=[col for col in df.columns if col.startswith('HORA')],
        var_name='HORA',
        value_name='VALOR'
    )

    # Convertir la columna HORA a número entero eliminando el prefijo "HORA"
    df_melted['HORA'] = df_melted['HORA'].str.replace('HORA', '').astype(int)

    # Manejo del caso especial: Si HORA es 24, moverlo al siguiente día y asignar 00:00:00
    df_melted.loc[df_melted['HORA'] == 24, 'FECHA'] = pd.to_datetime(df_melted['FECHA']) + pd.to_timedelta(1, unit='d')
    df_melted.loc[df_melted['HORA'] == 24, 'HORA'] = 0

    # Convertir HORA en formato timedelta para eliminar "0 days"
    df_melted['HORA'] = pd.to_timedelta(df_melted['HORA'], unit='h').astype(str).str.replace("0 days ", "")

    # Convertir la columna VALOR a formato numérico para evitar errores de conversión
    df_melted['VALOR'] = pd.to_numeric(df_melted['VALOR'], errors='coerce')

    # Pivotear para organizar por parámetros
    df_pivoted = df_melted.pivot_table(
        index=['CLAVE_EST', 'FECHA', 'HORA'],
        columns='PARAMETRO',
        values='VALOR',
        aggfunc='mean'
    ).reset_index()

    # Homogeneizar nombres de columnas
    columnas_homogeneas = {'O': 'O3'}
    df_pivoted.rename(columns=columnas_homogeneas, inplace=True)

    # Lista de columnas a eliminar
    columns_to_drop = ['STW', 'STWD', 'FILT', 'FLAM', 'THC', 'MHC']
    # Eliminar columnas solo si existen en el DataFrame
    df_pivoted = df_pivoted.drop(columns=[col for col in columns_to_drop if col in df_pivoted.columns])

    # Eliminar columnas con nombres duplicados en el índice
    df = df.loc[:, ~df.columns.duplicated()]
    
    # Guardar cada archivo procesado en la carpeta
    df_pivoted.to_excel(f'{carpeta_salida}/datos_{año}_homogeneizado.xlsx', index=False)

    print(f"Paso completado: Guardado como {carpeta_salida}/datos_{año}_homogeneizado.xlsx")

Procesando: datos_1996.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_1996_homogeneizado.xlsx
Procesando: datos_1997.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_1997_homogeneizado.xlsx
Procesando: datos_1998.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_1998_homogeneizado.xlsx
Procesando: datos_1999.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_1999_homogeneizado.xlsx
Procesando: datos_2000.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2000_homogeneizado.xlsx
Procesando: datos_2001.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2001_homogeneizado.xlsx
Procesando: datos_2002.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2002_homogeneizado.xlsx
Procesando: datos_2003.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2003_homogeneizado.xlsx
Procesando: datos_2004.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2004_homogeneizado.xlsx
Procesando: datos_2005.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2005_homogeneizado.xlsx
Procesando: datos_2006.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2006_homogeneizado.xlsx
Procesando: datos_2007.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2007_homogeneizado.xlsx
Procesando: datos_2008.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2008_homogeneizado.xlsx
Procesando: datos_2009.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2009_homogeneizado.xlsx
Procesando: datos_2010.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2010_homogeneizado.xlsx
Procesando: datos_2011.xlsx
Paso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2011_homogeneizado.xlsx

Este proceso de homogenización se realizó por cada base de datos, guardando los archivos procesados con el nombre de `datos_{año}_homogeneizado`. Estos nuevos archivos se concatenaron mediante el método `.append.()` y `.concat()`. El dataframe final comprende datos desde 1996 a 2011

In [5]:
# Inicialización de la Lista
archivos = []

# Asignación de los Archivos a la Lista
for año in range(1996, 2011+1):
    df = pd.read_excel(f'./Archivos/Datos/Homogeneizados/datos_{año}_homogeneizado.xlsx')

    # **Filtrar registros que correspondan al año del archivo**
    df = df[df['FECHA'].dt.year == año]

    # Eliminar columnas con nombres duplicados en el índice
    df = df.loc[:, ~df.columns.duplicated()]

    archivos.append(df)  # Agregar el DataFrame filtrado a la lista
    
# Concatenación de los Elementos de la Lista a un DataFrame
df_96_11 = pd.concat(archivos, ignore_index = True)

# Guardar el DataFrame final como CSV
ruta_guardado = "./Archivos/Datos/Homogeneizados/datos_1996_2011_homogeneizado.csv"
df_96_11.to_csv(ruta_guardado, index=False, encoding="utf-8")

# Mostrar el tipo de datos contenidos en el Dataframe
print('Tipos de Datos en el DataFrame:\n', df_96_11.dtypes)

# Impresión de los Resultados
display(df_96_11)

Tipos de Datos en el DataFrame:
 CLAVE_EST            object
FECHA        datetime64[ns]
HORA                 object
CO                  float64
NO2                 float64
NOX                 float64
O3                  float64
PM10                float64
RH                  float64
SO2                 float64
TMP                 float64
WDR                 float64
WSP                 float64
TMPI                float64
NO                  float64
STW                float64
PM25                float64
O3.1                float64
dtype: object

,CLAVE_EST,FECHA,HORA,CO,NO2,NOX,O3,PM10,RH,SO2,TMP,WDR,WSP,TMPI,NO,STW,PM25,O3.1
0,AGU,1996-01-01,01:00:00,0.6,16.000,17.000,38.000,221.7,73.9,1.000,12.6,237.4,12.3,NaN,NaN,NaN,NaN,NaN
1,AGU,1996-01-01,02:00:00,0.6,18.000,19.000,41.000,86.5,75.3,3.000,12.3,234.4,11.4,NaN,NaN,NaN,NaN,NaN
2,AGU,1996-01-01,03:00:00,0.7,17.000,17.000,38.000,296.8,75.0,3.000,11.6,243.7,10.4,NaN,NaN,NaN,NaN,NaN
3,AGU,1996-01-01,04:00:00,0.7,18.000,19.000,35.000,181.5,77.4,2.000,11.0,258.3,10.4,NaN,NaN,NaN,NaN,NaN
4,AGU,1996-01-01,05:00:00,0.7,19.000,19.000,35.000,129.7,75.2,1.000,10.6,266.5,6.8,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117326,VAL,2011-12-31,19:00:00,0.5,0.013,0.012,0.054,NaN,NaN,0.001,NaN,NaN,NaN,NaN,-0.001,NaN,NaN,NaN
1117327,VAL,2011-12-31,20:00:00,0.6,0.023,0.022,0.036,NaN,NaN,0.001,NaN,NaN,NaN,NaN,-0.001,NaN,NaN,NaN
1117328,VAL,2011-12-31,21:00:00,0.9,0.037,0.046,0.015,NaN,NaN,0.003,NaN,NaN,NaN,NaN,0.009,NaN,NaN,NaN
1117329,VAL,2011-12-31,22:00:00,0.7,0.027,0.027,0.019,NaN,NaN,0.001,NaN,NaN,NaN,NaN,0.001,NaN,NaN,NaN
1117330,VAL,2011-12-31,23:00:00,0.5,0.018,0.018,0.020,NaN,NaN,0.001,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN

### Periodo 2012-2018 y 2021
Para homogeneizar los datos monitoreo de la calidad del aire desde *2012* a *2018*, así como los datos de *2021*, se deben tener en cuenta los siguientes puntos: 
1. A diferencia de las bases de datos del periodo anterior, el presente periodo de datos tiene un formato donde los parámetros y contaminantes son columnas y las horas de monitoreo son renglones. Sin embargo, hay una diversidad de nombres asociados a los parámetros. Esta problemática de nomenclaturas de referencia también se repite en con el título de las columnas relacionadas con la fecha y hora de monitoreo.
2. Es necesario recolectar la información desde diferentes hojas de las bases de datos originales (hojas de cálculo de Excel). Cada hoja recopila el monitoreo de una estación por específico, con la problemática de la diversidad de nomenclaturas asociadas a cada estación.
3. Las bases de datos carecen de la columna con las claves de las estaciones, con excepción del archivo `datos_2021`.
4. Algunos archivos contienen mediciones no correspondientes al año de monitoreo o, incluso, hojas de cálculo que no se desean procesar porque están vacías o los datos no son de interés (explicación de nomenclaturas).
5. El archivo `datos_2014` contiene un procesamiento y generación de estadísticos que deben eliminarse .
6. La columna relacionada a las horas del archivo `datos_2021` no está en formato adecuado.
7. Algunas hojas de `datos_2016` no tienen título en las columnas de fechas y horas de monitoreo.

La metodología de homogenización se presenta a continuación:
1. `pd.ExcelFile()` carga el archivo Excel y obtiene las hojas disponibles.
2. `sheet_names` detecta automáticamente las hojas de cálculo que se refieren a las estaciones de monitoreo.
3. `empty` verifica si una hoja está vacía antes de procesarla.
4. `columns.empty` revisa si la hoja tiene columnas o está vacía.
5. `rename()` modifica los nombres de columnas para uniformarlas.
6. `apply()`  aplica funciones para eliminar estadísticos de `datos_2014`.
7. `str.contains()` filtra columnas según palabras clave específicas.
8. `pd.to_datetime()` convierte la columna de fechas (`FECHA`) al formato datetime.
9. `dropna()` elimina filas con valores vacíos o NaT en la columna de fechas.
10. `dt.year` extrae el año de cada fila para el filtrado.
11. `concat()` une todas las hojas procesadas en un solo DataFrame.
12. `pd.to_timedelta()` convierte una columna a formato de duración/tiempo.
13. `replace()` sustituye los nombres de columnas dentro del DataFrame.
14. `append()` acumula las hojas de cálculo procesadas en una lista para luego fusionarlas.

In [7]:
# Procesar los archivos de 2012 a 2018 y 2021
for año in [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2021]:
    print(f"Procesando: datos_{año}.xlsx")

    # Cargar archivo Excel y obtener hojas (estaciones)
    ruta_archivo = f'./Archivos/Datos/datos_{año}.xlsx'
    df_excel = pd.ExcelFile(ruta_archivo)
    hojas = df_excel.sheet_names  # Detectar estaciones

    # Lista para acumular los datos de todas las hojas
    df_total = []

    # Procesar cada hoja (estación)
    for hoja in hojas:
        print(f"   Procesando estación: {hoja}")

        # Leer cada hoja
        df = pd.read_excel(ruta_archivo, sheet_name=hoja)

        # Si la hoja no tiene columnas ni datos, se omite
        if df.empty or df.columns.empty:
            print(f"Advertencia: La hoja '{hoja}' en '{ruta_archivo}' está vacía y fue omitida.")
            continue  # Saltar a la siguiente hoja

        # Si la hoja es "Nomenclatura", saltarla
        if hoja == "Nomenclatura":
            print(f" Hoja '{hoja}' omitida en el archivo {ruta_archivo}.")
            continue  # Saltar a la siguiente hoja sin procesarla

        
        # Agregar nombre de estación
        df['ESTACION'] = hoja

        # Asignar nombres a las primeras columnas de 2016 que no tienen el título de FECHA y HORA
        if año == 2016:
            if hoja in ["Oblatos", "Las Pintas"]:
                df.columns = ['FECHA', 'HORA'] + df.columns[2:].tolist()  # Mantener el resto de columnas

        # Homogeneizar nombres de columnas
        columnas_homogeneas = {'Date': 'FECHA',
                               'Fecha': 'FECHA',
                               'Time': 'HORA',
                               'Hora': 'HORA',
                               'Santa Fé' : 'FECHA',
                               'Fecha ': 'FECHA', 
                               'Hora ': 'HORA', 
                               '1:O3': 'O3',
                               '17:O3': 'O3',
                               'Ozono': 'O3',
                               '18:NO': 'NO',
                               '3:NO2': 'NO2',
                               '19:NO2': 'NO2',
                               '20:NOx': 'NOx',
                               'Nox': 'NOx',
                               'NOX': 'NOx',
                               '5:SO2': 'SO2',
                               '21:SO2': 'SO2',
                               '6:CO': 'CO',
                               '22:CO': 'CO',
                               '7:PM10': 'PM10',
                              '7:PM 10': 'PM10',
                               'PM 10': 'PM10',
                              'PM 2.5': 'PM2.5',
                              'Pm2.5': 'PM2.5',
                              'Temp Int': 'TMPI',
                              'TempInt': 'TMPI',
                              'Temp Ext': 'TMP',
                              '9:Temp Ext': 'TMP',
                               'Temperatura exterior': 'TMP',
                               'TempExt': 'TMP',
                               'TEM EXT': 'TMP',
                               'Temperatura': 'TMP',
                               'Temperatura ': 'TMP',
                               'HR': 'RH',
                               '10:RH': 'RH',
                               'Humedad relativa': 'RH',
                               'Humedad relativa ': 'RH',
                               '11:WS': 'WS',
                               'Velocidad de viento': 'WS',
                               'Velocidad de viento ': 'WS',
                               '12:WD': 'WD',
                               'Dirección de vientos': 'WD',
                               'Dirección de vientos ': 'WD',
                               'Precipitación': 'PP',
                               'Precipitacion': 'PP',
                               'Pr': 'PP',
                               'Precipíta ': 'PP',
                               'Precipita ': 'PP',
                               'Precipíta': 'PP',
                               'Precipita': 'PP',                               
                               'Radiación solar': 'RS',
                               'Radiación solar ': 'RS',
                               'Radiacion Solar': 'RS',
                               'RadSolar': 'RS',
                               'Rad Solar': 'RS',
                               'Presión': 'PBA',
                               'Presion': 'PBA',
                               'índice UV': 'UVI',
                               'Índice UV': 'UVI'
                              }
        
        df.rename(columns=columnas_homogeneas, inplace=True)

        # Eliminar filas innecesarias del archivo de 2014
        if año == 2014:
            df = df[~df.apply(lambda row: row.astype(str).str.contains("SUMA|PROMEDIO|Mínima|Máxima").any(), axis=1)]

        if 'FECHA' in df.columns:
            df['FECHA'] = pd.to_datetime(df['FECHA'], errors='coerce')
            df = df.dropna(subset=['FECHA'])  # Eliminar filas con NaT
            df = df[df['FECHA'].dt.year == año]
        else:
            print(f"Advertencia: La hoja '{hoja}' en '{ruta_archivo}' no tiene columna FECHA. Se omitió el filtrado por año.")

        # Filtrar registros que no corresponden al año del archivo
        df = df[df['FECHA'].dt.year == año]

        # Lista de columnas a eliminar
        columns_to_drop = ['Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Pintas', 'Estación SIMAJ']
        # Eliminar columnas solo si existen en el DataFrame
        df = df.drop(columns=[col for col in columns_to_drop if col in df.columns])
                
        # Formatear HORA a hh:mm:ss si es numérica
        if df['HORA'].dtype in ['int64', 'float64']:  # Revisar si la columna es numérica
            df['HORA'] = pd.to_timedelta(df['HORA'], unit='h').astype(str).str.replace("0 days ", "")

        # Mover ESTACION a la primera columna
        cols = ['ESTACION'] + [col for col in df.columns if col != 'ESTACION']
        df = df[cols]

        # Acumular cada hoja en la lista
        df_total.append(df)

    # Concatenar todas las hojas del archivo en un solo DataFrame
    df_final = pd.concat(df_total, ignore_index=True)

    # Guardar cada archivo procesado en la carpeta
    df_final.to_excel(f'{carpeta_salida}/datos_{año}_homogeneizado.xlsx', index=False)

    print(f"Proceso completado: Guardado como {carpeta_salida}/datos_{año}_homogeneizado.xlsx")

Procesando: datos_2012.xlsx
   Procesando estación: AGU
   Procesando estación: ATE
   Procesando estación: CEN
   Procesando estación: LPIN
   Procesando estación: LDO
   Procesando estación: MIR
   Procesando estación: OBL
   Procesando estación: TLA
   Procesando estación: VAL
   Procesando estación: Hoja1
Advertencia: La hoja 'Hoja1' en './Archivos/Datos/datos_2012.xlsx' está vacía y fue omitida.
Proceso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2012_homogeneizado.xlsx
Procesando: datos_2013.xlsx
   Procesando estación: Aguilas
   Procesando estación: Atemajac
   Procesando estación: Centro
   Procesando estación: Las Pintas
   Procesando estación: Loma Dorada
   Procesando estación: Miravalle
   Procesando estación: Oblatos
   Procesando estación: Santa Fé
   Procesando estación: Tlaquepaque
   Procesando estación: Vallarta
   Procesando estación: Hoja1
Advertencia: La hoja 'Hoja1' en './Archivos/Datos/datos_2013.xlsx' está vacía y fue omitida.
Proceso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2013_homogeneizado.xlsx
Procesando: datos_2014.xlsx
   Procesando estación: Atemajac
   Procesando estación: Oblatos
   Procesando estación: Loma Dorada
   Procesando estación: Tlaquepaque
   Procesando estación: Centro
   Procesando estación: Vallarta
   Procesando estación: Aguilas
   Procesando estación: Miravalle
   Procesando estación: Las Pintas
   Procesando estación: Santa Fé
Proceso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2014_homogeneizado.xlsx
Procesando: datos_2015.xlsx
   Procesando estación: Atemajac
   Procesando estación: Águilas
   Procesando estación: Centro
   Procesando estación: Las Pintas
   Procesando estación: Loma Dorada
   Procesando estación: Miravalle
   Procesando estación: Oblatos
   Procesando estación: Santa Fe
   Procesando estación: Tlaquepaque
   Procesando estación: Vallarta
Proceso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2015_homogeneizado.xlsx
Procesando: datos_2016.xlsx
   Procesando estación: Atemajac
   Procesando estación: Oblatos
   Procesando estación: Las Pintas
   Procesando estación: Santa Fe
   Procesando estación: Tlaquepaque
   Procesando estación: Vallarta
   Procesando estación: Centro
   Procesando estación: Las Águilas
   Procesando estación: Loma Dorada
   Procesando estación: Miravalle
Proceso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2016_homogeneizado.xlsx
Procesando: datos_2017.xlsx
   Procesando estación: Atemajac

C:\Users\franc\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():
C:\Users\franc\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

   Procesando estación: Águilas
   Procesando estación: Loma dorada
   Procesando estación: Miravalle
   Procesando estación: Centro
   Procesando estación: Oblatos
   Procesando estación: Las Pintas
   Procesando estación: Tlaquepaque
   Procesando estación: Santa Fe
   Procesando estación: Vallarta
Proceso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2017_homogeneizado.xlsx
Procesando: datos_2018.xlsx
   Procesando estación: Águilas
   Procesando estación: Atemajac
   Procesando estación: Centro
   Procesando estación: Las Pintas
   Procesando estación: Loma Dorada
   Procesando estación: Miravalle
   Procesando estación: Oblatos
   Procesando estación: Santa Fe
   Procesando estación: Tlaquepaque
   Procesando estación: Vallarta
Proceso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2018_homogeneizado.xlsx
Procesando: datos_2021.xlsx
   Procesando estación: AGU
   Procesando estación: ATM
   Procesando estación: CEN
   Procesando estación: PIN
   Procesando estación: LDO
   Procesando estación: MIR
   Procesando estación: OBL
   Procesando estación: SFE
   Procesando estación: TLA
   Procesando estación: VAL
   Procesando estación: Nomenclatura
 Hoja 'Nomenclatura' omitida en el archivo ./Archivos/Datos/datos_2021.xlsx.
Proceso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2021_homogeneizado.xlsx

Este proceso de homogenización se realizó por cada base de datos, guardando los archivos procesados con el nombre de `datos_{año}_homogeneizado`. Estos nuevos archivos se concatenaron mediante el método `.append.()` y `.concat()`. El dataframe final comprende datos desde **2011** a **2018**, incluyendo **2021**.

In [17]:
# Inicialización de la Lista
archivos = []

# Asignación de los Archivos a la Lista
for año in [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2021]:
    df = pd.read_excel(f'./Archivos/Datos/Homogeneizados/datos_{año}_homogeneizado.xlsx')

    # Filtrar registros que no corresponden al año del archivo
    df = df[df['FECHA'].dt.year == año]
    df['HORA'] = pd.to_datetime(df['HORA'], format='%H:%M:%S', errors='coerce').dt.time

    archivos.append(df)  # Agregar el DataFrame filtrado a la lista
    
# Concatenación de los Elementos de la Lista a un DataFrame
df_12_18_21 = pd.concat(archivos, ignore_index = True)

# Guardar el DataFrame final como CSV
ruta_guardado = "./Archivos/Datos/Homogeneizados/datos_2012_2018_2021_homogeneizado.csv"
df_12_18_21.to_csv(ruta_guardado, index=False, encoding="utf-8")

# Mostrar el tipo de datos contenidos en el Dataframe
print('Tipos de Datos en el DataFrame:\n', df_12_18_21.dtypes)

# Impresión de los Resultados
display(df_12_18_21)

Tipos de Datos en el DataFrame:
 ESTACION            object
FECHA       datetime64[ns]
HORA                object
O3                  object
NO2                 object
SO2                 object
CO                  object
PM10                object
TMP                 object
RH                  object
WS                  object
WD                  object
NO                  object
NOx                 object
PP                  object
PM2.5               object
RS                  object
UV                  object
UVI                 object
PBA                 object
TMPI                object
dtype: object

,ESTACION,FECHA,HORA,O3,NO2,SO2,CO,PM10,TMP,RH,...,WD,NO,NOx,PP,PM2.5,RS,UV,UVI,PBA,TMPI
0,AGU,2012-01-01,00:00:00,0.018,0.036,0.002,0.478,13.6,18.9,49.6,...,256.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AGU,2012-01-01,01:00:00,0.022,0.028,0.002,0.573,12.1,18.5,52.3,...,262.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AGU,2012-01-01,02:00:00,0.009,0.044,0.003,1.298,15.4,17.3,55.3,...,204.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AGU,2012-01-01,03:00:00,0.004,0.045,0.006,3.174,28.2,16.1,60.3,...,158.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AGU,2012-01-01,04:00:00,0.005,0.057,0.004,2.718,31.9,15.3,61.9,...,252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673423,VAL,2021-12-31,19:00:00,0.023,,0.0005,,21.5,23.3,32.3,...,226.6,,,0,19.9,NaN,0.01,0.22,NaN,22.8
673424,VAL,2021-12-31,20:00:00,0.023,,0.0005,,31.8,22.2,35.9,...,224.4,,,0,25,NaN,0.01,0.22,NaN,22.8
673425,VAL,2021-12-31,21:00:00,0.024,,0.0007,,29.4,19.9,51.1,...,241,,,0,25.6,NaN,0.01,0.21,NaN,22.8
673426,VAL,2021-12-31,22:00:00,0.02,,0.0009,,32.6,19.1,56.2,...,239.6,,,0,28.1,NaN,0.01,0.21,NaN,22.7
673427,VAL,2021-12-31,23:00:00,0.025,,0.0006,,25.8,18.3,65.1,...,239.7,,,0,25.5,NaN,0.01,0.21,NaN,22.7

### Periodo 2019-2023
Para homogeneizar los datos monitoreo de la calidad del aire desde **2019** a **2023** se deben tener en cuenta los siguientes puntos: 
1. Aunque todos los archivos contienen los datos de interés en una única hoja de cálculo, hay bases de datos con hojas adicionales que no serán procesadas.
2. Se deberán homogeneizar los nombres de columnas (parámetros de medición).
3. Algunos archivos contienen mediciones no correspondientes al año de monitoreo o, incluso, hojas de cálculo que no se desean procesar porque están vacías o los datos no son de interés (explicación de nomenclaturas).

En este sentido, la metodología de homogenización fue similar al procesamiento del periodo anterior de bases de datos.

In [9]:
# Procesar los archivos de 2019 a 2023, uno por uno
for año in [2019, 2020, 2022, 2023]:
    print(f"Procesando: datos_{año}.xlsx")  # Mensaje de seguimiento

    # Cargar archivo Excel y obtener hojas (datos)
    ruta_archivo = f'./Archivos/Datos/datos_{año}.xlsx'
    df_excel = pd.ExcelFile(ruta_archivo)
    hojas = df_excel.sheet_names  # Detectar hojas con datos

    # Lista para acumular los datos de todas las hojas
    df_total = []

    # Procesar cada hoja (datos)
    for hoja in hojas:
        print(f"   Procesando estación: {hoja}")

        # Leer cada hoja
        df = pd.read_excel(ruta_archivo, sheet_name=hoja)

        # Si la hoja no tiene columnas ni datos, se omite
        if df.empty or df.columns.empty:
            print(f"Advertencia: La hoja '{hoja}' en '{ruta_archivo}' está vacía y fue omitida.")
            continue  # Saltar a la siguiente hoja

        # Omitir hojas sin datos de interes
        hojas_excluir = ['Nomenclatura-Unidad de medida ', 'Estaciones-Ubicación', 'unidades y parámetros']

        if hoja in hojas_excluir:
            print(f" Hoja '{hoja}' omitida en el archivo {ruta_archivo}.")
            continue  # Saltar a la siguiente hoja sin procesarla

        # Homogeneizar nombres de columnas
        columnas_homogeneas = {'Date_Time': 'FECHA',
                               'Fecha': 'FECHA',
                               'FECHA ': 'FECHA',
                               'Hora': 'HORA',
                               'HORA ': 'HORA',
                               'Estación': 'ESTACIÓN',
                               'CO ': 'CO',
                               'NO2 ': 'NO2',
                               'NOX': 'NOx',
                               'NOX ': 'NOx',
                               'PM10 ': 'PM10',
                               'PM 2.5': 'PM2.5',
                               'Temp Int': 'TMPI',
                               'Temp Int ': 'TMPI',
                               'Temp Ext': 'TMP',
                               'Precipitación': 'PP',
                               'PRECIPITACION': 'PP',
                               'PRECIPITACION ': 'PP',
                               'RH ': 'RH',
                               'Radiación Solar': 'RS',
                               'Radiación Solar ': 'RS',
                               'Rad Solar': 'RS',
                               'Presión Barometrica': 'PBA',
                               'PRESION BAROMETRICA': 'PBA',
                               'PRESION BAROMETRICA ': 'PBA',
                              }
        
        df.rename(columns=columnas_homogeneas, inplace=True)

        # Filtrar registros que no corresponden al año del archivo
        df = df[df['FECHA'].dt.year == año]
                
        # Formatear HORA a hh:mm:ss si es numérica
        if df['HORA'].dtype in ['int64', 'float64']:  # Revisar si la columna es numérica
            df['HORA'] = pd.to_timedelta(df['HORA'], unit='h').astype(str).str.replace("0 days ", "")

        # Mover ESTACION a la primera columna
        cols = ['ESTACIÓN'] + [col for col in df.columns if col != 'ESTACIÓN']
        df = df[cols]

        # Acumular cada hoja en la lista
        df_total.append(df)

    # Concatenar todas las hojas del archivo en un solo DataFrame
    df_final = pd.concat(df_total, ignore_index=True)

    # Guardar cada archivo procesado en la carpeta
    df_final.to_excel(f'{carpeta_salida}/datos_{año}_homogeneizado.xlsx', index=False)

    print(f"Proceso completado: Guardado como {carpeta_salida}/datos_{año}_homogeneizado.xlsx")

Procesando: datos_2019.xlsx
   Procesando estación: BD_SIMAJ2019
Proceso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2019_homogeneizado.xlsx
Procesando: datos_2020.xlsx
   Procesando estación: BD10 2020 SIMAJ (REV)

C:\Users\franc\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

   Procesando estación: Nomenclatura-Unidad de medida
 Hoja 'Nomenclatura-Unidad de medida ' omitida en el archivo ./Archivos/Datos/datos_2020.xlsx.
Proceso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2020_homogeneizado.xlsx
Procesando: datos_2022.xlsx
   Procesando estación: SIMAJ 2022
   Procesando estación: Estaciones-Ubicación
 Hoja 'Estaciones-Ubicación' omitida en el archivo ./Archivos/Datos/datos_2022.xlsx.
Proceso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2022_homogeneizado.xlsx
Procesando: datos_2023.xlsx
   Procesando estación: base datos 2023
   Procesando estación: unidades y parámetros
 Hoja 'unidades y parámetros' omitida en el archivo ./Archivos/Datos/datos_2023.xlsx.
Proceso completado: Guardado como ./Archivos/Datos/Homogeneizados/datos_2023_homogeneizado.xlsx

Este proceso de homogenización se realizó por cada base de datos, guardando los archivos procesados con el nombre de `datos_{año}_homogeneizado`. Estos nuevos archivos se concatenaron mediante el método `.append.()` y `.concat()`. El dataframe final comprende datos desde **2019** a **2023**.

In [19]:
# Inicialización de la Lista
archivos = []

# Asignación de los Archivos a la Lista
for año in [2019, 2020, 2022, 2023]:
    df = pd.read_excel(f'./Archivos/Datos/Homogeneizados/datos_{año}_homogeneizado.xlsx')

    # Filtrar registros que no corresponden al año del archivo
    df = df[df['FECHA'].dt.year == año]
    df['HORA'] = pd.to_datetime(df['HORA'], format='%H:%M:%S', errors='coerce').dt.time

    archivos.append(df)  # Agregar el DataFrame filtrado a la lista
    
# Concatenación de los Elementos de la Lista a un DataFrame
df_19_23 = pd.concat(archivos, ignore_index = True)

# Guardar el DataFrame final como CSV
ruta_guardado = "./Archivos/Datos/Homogeneizados/datos_2019_2023_homogeneizado.csv"
df_19_23.to_csv(ruta_guardado, index=False, encoding="utf-8")

# Mostrar el tipo de datos contenidos en el Dataframe
print('Tipos de Datos en el DataFrame:\n', df_19_23.dtypes)

# Impresión de los Resultados
display(df_19_23)

Tipos de Datos en el DataFrame:
 ESTACIÓN            object
FECHA       datetime64[ns]
HORA                object
O3                  object
NO                  object
NO2                 object
NOx                 object
SO2                 object
CO                  object
PM10                object
PM2.5               object
TMPI                object
TMP                 object
RH                  object
WS                  object
WD                  object
PP                  object
PBA                 object
RS                  object
UVI                 object
dtype: object

,ESTACIÓN,FECHA,HORA,O3,NO,NO2,NOx,SO2,CO,PM10,PM2.5,TMPI,TMP,RH,WS,WD,PP,PBA,RS,UVI
0,Aguilas,2019-01-01 00:00:00,00:00:00,0.003,0.006,0.01,0.016,0.0024,1.814,NaN,NaN,20.3,15.2,67.8,1.03,253.93,NaN,NaN,NaN,NaN
1,Aguilas,2019-01-01 00:00:00,01:00:00,0.002,0.008,0.009,0.017,0.0026,1.578,NaN,NaN,20.5,14.5,70.5,1.81,249.91,NaN,NaN,NaN,NaN
2,Aguilas,2019-01-01 00:00:00,02:00:00,0.003,0.017,0.009,0.026,0.0026,1.897,NaN,NaN,20.4,14.2,72.7,0.95,220.56,NaN,NaN,NaN,NaN
3,Aguilas,2019-01-01 00:00:00,03:00:00,0.003,0.017,0.009,0.026,0.0027,2.359,NaN,NaN,20.5,13.9,75.1,0.27,271.42,NaN,NaN,NaN,NaN
4,Aguilas,2019-01-01 00:00:00,04:00:00,0.003,0.017,0.008,0.025,0.0025,2.021,NaN,NaN,20.5,13.3,77.6,1.59,229.42,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350636,Vallarta,2023-12-31 19:00:00,19:00:00,0.04,SE,SE,SE,IO,SE,27.6,IO,22.8,22,38.8,8.79,IO,ND,631.95,SE,ND
350637,Vallarta,2023-12-31 20:00:00,20:00:00,0.042,SE,SE,SE,IO,SE,26.1,IO,22.8,21.19,38.9,2.37,IO,ND,632.46,SE,ND
350638,Vallarta,2023-12-31 21:00:00,21:00:00,0.034,SE,SE,SE,IO,SE,23.2,IO,22.7,20.79,38.9,0.57,IO,ND,632.9,SE,ND
350639,Vallarta,2023-12-31 22:00:00,22:00:00,0.03,SE,SE,SE,IO,SE,29.4,IO,22.7,20.31,39,6.51,1.9,ND,633.07,SE,ND
350640,Vallarta,2023-12-31 23:00:00,23:00:00,0.031,SE,SE,SE,IO,SE,35.2,IO,22.7,19.03,39.1,0.04,IO,ND,633.02,SE,ND

### Creación del Dataframe final (1996 a 2023)
Los objetivos de este nuevo procesamiento son:
1. Concatenar todas las bases de datos homogeneizadas
2. Proponer la nomenclatura final de parámetros, estaciones de monitoreo y los nombres de otras columnas. 
3. Convertir a valores numéricos tipo flotantes los valores de medición para facilitar la realización de estadísticos y gráficos mediante `pd.to.numeric()`.

In [21]:
# Diccionario de homologación de nombres de columnas
homologacion_columnas = {'ESTACION': 'CLAVE_EST',
                         'ESTACIÓN': 'CLAVE_EST',
                         'NOx': 'NOX',
                         'WDR': 'WD',
                         'WSP': 'WS',
                        }

# **Aplicar homologación a cada DataFrame antes de unirlos**
df_96_11 = df_96_11.rename(columns=homologacion_columnas)
df_12_18_21 = df_12_18_21.rename(columns=homologacion_columnas)
df_19_23 = df_19_23.rename(columns=homologacion_columnas)


# Concatenar los DataFrames en uno solo
df_final = pd.concat([df_96_11, df_12_18_21, df_19_23], ignore_index=True)

# Para asegurar que los datos estén bien organizados por año
#df_final = df_final.sort_values(by="FECHA")

# Lista de parámetros que deben ser float
columnas_parametros = ['O3', 'NO2', 'NO','NOX', 'CO', 'SO2', 'PM10', 'PM2.5', 'TMP', 'TMPI', 'RH', 'PP', 'WS', 'WD', 'RS', 'PBA','UV', 'UVI']

# Convertir a float, ignorando errores
df_final[columnas_parametros] = df_final[columnas_parametros].apply(pd.to_numeric, errors='coerce')

# Diccionario de homologación de nombres
homologacion_estaciones = {
    'Aguilas': 'AGU',
    'Aguilas ': 'AGU',
    'Águilas': 'AGU',
    'Águilas ': 'AGU',
    'Las Águilas': 'AGU',
    'Las Águilas ': 'AGU',
    'AGU ': 'AGU',
    'ATE': 'ATM',
    'ATE ': 'ATM',
    'Atemajac': 'ATM',
    'Atemajac ': 'ATM',
    'ATM ': 'ATM',
    'CEN ': 'CEN',
    'Centro': 'CEN',
    'Centro ': 'CEN',
    'LDO ': 'LDO',
    'Loma Dorada': 'LDO',
    'Loma Dorada ': 'LDO',
    'Loma dorada': 'LDO',
    'Loma dorada ': 'LDO',
    'MIR ': 'MIR',
    'Miravalle': 'MIR',
    'Miravalle ': 'MIR',
    'Oblatos': 'OBL',
    'Oblatos ': 'OBL',
    'OBL ': 'OBL',
    'PIN ': 'PIN',
    'LPIN': 'PIN',
    'LPIN ': 'PIN',
    'Las Pintas': 'PIN',
    'Las Pintas ': 'PIN',
    'SFE ': 'SFE',
    'Santa Fé': 'SFE',
    'Santa Fé ': 'SFE',
    'Santa Fe': 'SFE',
    'Santa Fe ': 'SFE',
    'TLA ': 'TLA',
    'Tlaquepaque': 'TLA',
    'Tlaquepaque ': 'TLA',
    'VAL ': 'VAL',
    'Vallarta': 'VAL',
    'Vallarta ': 'VAL',
    'VAL ': 'VAL'
}

df_final['CLAVE_EST'] = df_final['CLAVE_EST'].replace(homologacion_estaciones)

df_final['FECHA'] = pd.to_datetime(df_final['FECHA'], errors='coerce')

# Guardar el DataFrame final como CSV
ruta_guardado = "./Archivos/Datos/Homogeneizados/datos_1996_2023_homogeneizado.csv"
df_final.to_csv(ruta_guardado, index=False, encoding="utf-8")

print(f"✔ Archivo guardado exitosamente en: {ruta_guardado}")

# Mostrar el tipo de datos contenidos en el Dataframe
print('Tipos de Datos en el DataFrame:\n', df_final.dtypes)

# Impresión de los Resultados
display(df_final)

✔ Archivo guardado exitosamente en: ./Archivos/Datos/Homogeneizados/datos_1996_2023_homogeneizado.csv
Tipos de Datos en el DataFrame:
 CLAVE_EST            object
FECHA        datetime64[ns]
HORA                 object
CO                  float64
NO2                 float64
NOX                 float64
O3                  float64
PM10                float64
RH                  float64
SO2                 float64
TMP                 float64
WD                  float64
WS                  float64
TMPI                float64
NO                  float64
STW                float64
PM25                float64
O3.1                float64
PP                  float64
PM2.5               float64
RS                  float64
UV                  float64
UVI                 float64
PBA                 float64
dtype: object

,CLAVE_EST,FECHA,HORA,CO,NO2,NOX,O3,PM10,RH,SO2,...,NO,STW,PM25,O3.1,PP,PM2.5,RS,UV,UVI,PBA
0,AGU,1996-01-01 00:00:00,01:00:00,0.6,16.0,17.0,38.000,221.7,73.9,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AGU,1996-01-01 00:00:00,02:00:00,0.6,18.0,19.0,41.000,86.5,75.3,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AGU,1996-01-01 00:00:00,03:00:00,0.7,17.0,17.0,38.000,296.8,75.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AGU,1996-01-01 00:00:00,04:00:00,0.7,18.0,19.0,35.000,181.5,77.4,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AGU,1996-01-01 00:00:00,05:00:00,0.7,19.0,19.0,35.000,129.7,75.2,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2141395,VAL,2023-12-31 19:00:00,19:00:00,NaN,NaN,NaN,0.040,27.6,38.8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,631.95
2141396,VAL,2023-12-31 20:00:00,20:00:00,NaN,NaN,NaN,0.042,26.1,38.9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,632.46
2141397,VAL,2023-12-31 21:00:00,21:00:00,NaN,NaN,NaN,0.034,23.2,38.9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,632.90
2141398,VAL,2023-12-31 22:00:00,22:00:00,NaN,NaN,NaN,0.030,29.4,39.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,633.07
2141399,VAL,2023-12-31 23:00:00,23:00:00,NaN,NaN,NaN,0.031,35.2,39.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,633.02

## 4. Comunicación del proyecto
Con la finalidad de compartir los resultados del presente proyecto, se decidió publicar la base de datos final en `Streamlit` junto con un gráfico modificable que les permita a los usuarios explorar los datos fácilmente, seleccionando estación de monitoreo, año y contaminante o parámetro de interés. De esta manera, se podrán observar tendencias mensuales y compararlas en diferentes periodos o épocas en diferentes años. 

https://calidad-del-aire-6gqhwurrgs2eeyp4gfyhmd.streamlit.app/

<center><img src="./Archivos/Imagenes/Imagen7.png" style="width:750px;height:900px;" class="center"></center>

## 5. Análisis sugeridos:

**Tendencias temporales**
•	Analizar cómo han cambiado las concentraciones de contaminantes a lo largo del tiempo. ¿Hay una mejora o empeoramiento desde 1996 en el AMG?
•	Estudiar patrones estacionales. Por ejemplo, ¿la calidad del aire tiende a ser peor en ciertas épocas del año?

**Correlaciones climatológicas**
•	Explorar las relaciones entre los contaminantes y factores como la temperatura, humedad, radiación solar o precipitación.
•	Analiza cómo eventos climáticos extremos (picos de calor, lluvias intensas, etc.) afectan los niveles de contaminación.

**Comparación entre estaciones**
•	Identificar cuáles estaciones de monitoreo tienen los peores niveles de contaminación y cuales consistentemente presentan mejor calidad del aire.
•	Analizar si las ubicaciones de las estaciones influyen (por ejemplo, zonas habitacionales vs. zonas industriales).

**Impactos de políticas públicas**
•	Monitorear la calidad del aire tras la implementación de ciertas políticas ambientales, como la incorporación del programa Verificación Responsable, normativas sobre emisiones industriales o la veda para la quema de ladrillo

**Episodios críticos**
•	Identificación de días u horas con niveles de contaminación altos y examinar qué factores pudieron influir. ¿Coinciden con eventos específicos, como incendios forestales o alta actividad vehicular?

**Predicciones y modelos**
•	Usar los datos históricos para entrenar modelos predictivos de calidad del aire en función de variables climáticas y patrones históricos.

**Impactos de largo plazo y cambio climático**
•	Estudiar si la calidad del aire tiene relación con el cambio climático local: ¿las temperaturas promedio han cambiado junto con los contaminantes?

**Visualización y comunicación**
•	Crear mapas de calor que muestren la concentración de contaminantes.
•	Diseñar gráficos que expliquen los datos de una forma que pueda influir en políticas o campañas de concientización.